name: rest
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6+1
  get: ^4.6.5
  shared_preferences: ^2.0.17
  sqflite: ^2.2.4+1
  http: ^0.13.5
  awesome_dialog: ^3.0.2
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
